# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cad_model1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cad_model1.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61\x64_model1.proto\"\x1e\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\">\n\x0bPointEntity\x12\x17\n\x0fis_construction\x18\x01 \x01(\x08\x12\x16\n\x05point\x18\x02 \x01(\x0b\x32\x07.Vector\"\x89\x01\n\nLineEntity\x12\x17\n\x0fis_construction\x18\x01 \x01(\x08\x12!\n\x05start\x18\x02 \x01(\x0b\x32\x12.LineEntity.Vector\x12\x1f\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x12.LineEntity.Vector\x1a\x1e\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\xa3\x01\n\x10MirrorConstraint\x12\x1c\n\x06mirror\x18\x01 \x01(\x0b\x32\x0c.PointEntity\x12.\n\x0emirrored_pairs\x18\x02 \x03(\x0b\x32\x16.MirrorConstraint.Pair\x1a\x41\n\x04Pair\x12\x1b\n\x05\x66irst\x18\x01 \x01(\x0b\x32\x0c.PointEntity\x12\x1c\n\x06second\x18\x02 \x01(\x0b\x32\x0c.PointEntity\"\xf1\x01\n\x06Sketch\x12\x1f\n\x07objects\x18\x01 \x03(\x0b\x32\x0e.Sketch.Object\x1a-\n\x06\x45ntity\x12\x1b\n\x04line\x18\x01 \x01(\x0b\x32\x0b.LineEntityH\x00\x42\x06\n\x04kind\x1a\x39\n\nConstraint\x12#\n\x06mirror\x18\x01 \x01(\x0b\x32\x11.MirrorConstraintH\x00\x42\x06\n\x04kind\x1a\\\n\x06Object\x12 \n\x06\x65ntity\x18\x01 \x01(\x0b\x32\x0e.Sketch.EntityH\x00\x12(\n\nconstraint\x18\x02 \x01(\x0b\x32\x12.Sketch.ConstraintH\x00\x42\x06\n\x04kindb\x06proto3'
)




_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=50,
)


_POINTENTITY = _descriptor.Descriptor(
  name='PointEntity',
  full_name='PointEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_construction', full_name='PointEntity.is_construction', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point', full_name='PointEntity.point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=114,
)


_LINEENTITY_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='LineEntity.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='LineEntity.Vector.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='LineEntity.Vector.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=50,
)

_LINEENTITY = _descriptor.Descriptor(
  name='LineEntity',
  full_name='LineEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_construction', full_name='LineEntity.is_construction', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='LineEntity.start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='LineEntity.end', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LINEENTITY_VECTOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=254,
)


_MIRRORCONSTRAINT_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='MirrorConstraint.Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='MirrorConstraint.Pair.first', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='second', full_name='MirrorConstraint.Pair.second', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=420,
)

_MIRRORCONSTRAINT = _descriptor.Descriptor(
  name='MirrorConstraint',
  full_name='MirrorConstraint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mirror', full_name='MirrorConstraint.mirror', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mirrored_pairs', full_name='MirrorConstraint.mirrored_pairs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MIRRORCONSTRAINT_PAIR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=420,
)


_SKETCH_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='Sketch.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='Sketch.Entity.line', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='Sketch.Entity.kind',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=466,
  serialized_end=511,
)

_SKETCH_CONSTRAINT = _descriptor.Descriptor(
  name='Constraint',
  full_name='Sketch.Constraint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mirror', full_name='Sketch.Constraint.mirror', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='Sketch.Constraint.kind',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=513,
  serialized_end=570,
)

_SKETCH_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='Sketch.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity', full_name='Sketch.Object.entity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='constraint', full_name='Sketch.Object.constraint', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='Sketch.Object.kind',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=572,
  serialized_end=664,
)

_SKETCH = _descriptor.Descriptor(
  name='Sketch',
  full_name='Sketch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='Sketch.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SKETCH_ENTITY, _SKETCH_CONSTRAINT, _SKETCH_OBJECT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=664,
)

_POINTENTITY.fields_by_name['point'].message_type = _VECTOR
_LINEENTITY_VECTOR.containing_type = _LINEENTITY
_LINEENTITY.fields_by_name['start'].message_type = _LINEENTITY_VECTOR
_LINEENTITY.fields_by_name['end'].message_type = _LINEENTITY_VECTOR
_MIRRORCONSTRAINT_PAIR.fields_by_name['first'].message_type = _POINTENTITY
_MIRRORCONSTRAINT_PAIR.fields_by_name['second'].message_type = _POINTENTITY
_MIRRORCONSTRAINT_PAIR.containing_type = _MIRRORCONSTRAINT
_MIRRORCONSTRAINT.fields_by_name['mirror'].message_type = _POINTENTITY
_MIRRORCONSTRAINT.fields_by_name['mirrored_pairs'].message_type = _MIRRORCONSTRAINT_PAIR
_SKETCH_ENTITY.fields_by_name['line'].message_type = _LINEENTITY
_SKETCH_ENTITY.containing_type = _SKETCH
_SKETCH_ENTITY.oneofs_by_name['kind'].fields.append(
  _SKETCH_ENTITY.fields_by_name['line'])
_SKETCH_ENTITY.fields_by_name['line'].containing_oneof = _SKETCH_ENTITY.oneofs_by_name['kind']
_SKETCH_CONSTRAINT.fields_by_name['mirror'].message_type = _MIRRORCONSTRAINT
_SKETCH_CONSTRAINT.containing_type = _SKETCH
_SKETCH_CONSTRAINT.oneofs_by_name['kind'].fields.append(
  _SKETCH_CONSTRAINT.fields_by_name['mirror'])
_SKETCH_CONSTRAINT.fields_by_name['mirror'].containing_oneof = _SKETCH_CONSTRAINT.oneofs_by_name['kind']
_SKETCH_OBJECT.fields_by_name['entity'].message_type = _SKETCH_ENTITY
_SKETCH_OBJECT.fields_by_name['constraint'].message_type = _SKETCH_CONSTRAINT
_SKETCH_OBJECT.containing_type = _SKETCH
_SKETCH_OBJECT.oneofs_by_name['kind'].fields.append(
  _SKETCH_OBJECT.fields_by_name['entity'])
_SKETCH_OBJECT.fields_by_name['entity'].containing_oneof = _SKETCH_OBJECT.oneofs_by_name['kind']
_SKETCH_OBJECT.oneofs_by_name['kind'].fields.append(
  _SKETCH_OBJECT.fields_by_name['constraint'])
_SKETCH_OBJECT.fields_by_name['constraint'].containing_oneof = _SKETCH_OBJECT.oneofs_by_name['kind']
_SKETCH.fields_by_name['objects'].message_type = _SKETCH_OBJECT
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['PointEntity'] = _POINTENTITY
DESCRIPTOR.message_types_by_name['LineEntity'] = _LINEENTITY
DESCRIPTOR.message_types_by_name['MirrorConstraint'] = _MIRRORCONSTRAINT
DESCRIPTOR.message_types_by_name['Sketch'] = _SKETCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'cad_model1_pb2'
  # @@protoc_insertion_point(class_scope:Vector)
  })
_sym_db.RegisterMessage(Vector)

PointEntity = _reflection.GeneratedProtocolMessageType('PointEntity', (_message.Message,), {
  'DESCRIPTOR' : _POINTENTITY,
  '__module__' : 'cad_model1_pb2'
  # @@protoc_insertion_point(class_scope:PointEntity)
  })
_sym_db.RegisterMessage(PointEntity)

LineEntity = _reflection.GeneratedProtocolMessageType('LineEntity', (_message.Message,), {

  'Vector' : _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
    'DESCRIPTOR' : _LINEENTITY_VECTOR,
    '__module__' : 'cad_model1_pb2'
    # @@protoc_insertion_point(class_scope:LineEntity.Vector)
    })
  ,
  'DESCRIPTOR' : _LINEENTITY,
  '__module__' : 'cad_model1_pb2'
  # @@protoc_insertion_point(class_scope:LineEntity)
  })
_sym_db.RegisterMessage(LineEntity)
_sym_db.RegisterMessage(LineEntity.Vector)

MirrorConstraint = _reflection.GeneratedProtocolMessageType('MirrorConstraint', (_message.Message,), {

  'Pair' : _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), {
    'DESCRIPTOR' : _MIRRORCONSTRAINT_PAIR,
    '__module__' : 'cad_model1_pb2'
    # @@protoc_insertion_point(class_scope:MirrorConstraint.Pair)
    })
  ,
  'DESCRIPTOR' : _MIRRORCONSTRAINT,
  '__module__' : 'cad_model1_pb2'
  # @@protoc_insertion_point(class_scope:MirrorConstraint)
  })
_sym_db.RegisterMessage(MirrorConstraint)
_sym_db.RegisterMessage(MirrorConstraint.Pair)

Sketch = _reflection.GeneratedProtocolMessageType('Sketch', (_message.Message,), {

  'Entity' : _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
    'DESCRIPTOR' : _SKETCH_ENTITY,
    '__module__' : 'cad_model1_pb2'
    # @@protoc_insertion_point(class_scope:Sketch.Entity)
    })
  ,

  'Constraint' : _reflection.GeneratedProtocolMessageType('Constraint', (_message.Message,), {
    'DESCRIPTOR' : _SKETCH_CONSTRAINT,
    '__module__' : 'cad_model1_pb2'
    # @@protoc_insertion_point(class_scope:Sketch.Constraint)
    })
  ,

  'Object' : _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
    'DESCRIPTOR' : _SKETCH_OBJECT,
    '__module__' : 'cad_model1_pb2'
    # @@protoc_insertion_point(class_scope:Sketch.Object)
    })
  ,
  'DESCRIPTOR' : _SKETCH,
  '__module__' : 'cad_model1_pb2'
  # @@protoc_insertion_point(class_scope:Sketch)
  })
_sym_db.RegisterMessage(Sketch)
_sym_db.RegisterMessage(Sketch.Entity)
_sym_db.RegisterMessage(Sketch.Constraint)
_sym_db.RegisterMessage(Sketch.Object)


# @@protoc_insertion_point(module_scope)
