# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cad_model2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cad_model2.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61\x64_model2.proto\"\x1e\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\">\n\x0bPointEntity\x12\x17\n\x0fis_construction\x18\x01 \x01(\x08\x12\x16\n\x05point\x18\x02 \x01(\x0b\x32\x07.Vector\"S\n\nLineEntity\x12\x17\n\x0fis_construction\x18\x01 \x01(\x08\x12\x16\n\x05start\x18\x02 \x01(\x0b\x32\x07.Vector\x12\x14\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x07.Vector\"\xb3\x02\n\x0f\x43ircleArcEntity\x12\x17\n\x0fis_construction\x18\x01 \x01(\x08\x12\x17\n\x06\x63\x65nter\x18\x02 \x01(\x0b\x32\x07.Vector\x12\x36\n\rcircle_params\x18\x03 \x01(\x0b\x32\x1d.CircleArcEntity.CircleParamsH\x00\x12\x30\n\narc_params\x18\x04 \x01(\x0b\x32\x1a.CircleArcEntity.ArcParamsH\x00\x1a\x1e\n\x0c\x43ircleParams\x12\x0e\n\x06radius\x18\x01 \x01(\x01\x1aO\n\tArcParams\x12\x16\n\x05start\x18\x01 \x01(\x0b\x32\x07.Vector\x12\x14\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x07.Vector\x12\x14\n\x0cis_clockwise\x18\x03 \x01(\x08\x42\x13\n\x11\x61\x64\x64itional_paramsb\x06proto3'
)




_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=50,
)


_POINTENTITY = _descriptor.Descriptor(
  name='PointEntity',
  full_name='PointEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_construction', full_name='PointEntity.is_construction', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point', full_name='PointEntity.point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=114,
)


_LINEENTITY = _descriptor.Descriptor(
  name='LineEntity',
  full_name='LineEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_construction', full_name='LineEntity.is_construction', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='LineEntity.start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='LineEntity.end', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=199,
)


_CIRCLEARCENTITY_CIRCLEPARAMS = _descriptor.Descriptor(
  name='CircleParams',
  full_name='CircleArcEntity.CircleParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='radius', full_name='CircleArcEntity.CircleParams.radius', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=407,
)

_CIRCLEARCENTITY_ARCPARAMS = _descriptor.Descriptor(
  name='ArcParams',
  full_name='CircleArcEntity.ArcParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='CircleArcEntity.ArcParams.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='CircleArcEntity.ArcParams.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_clockwise', full_name='CircleArcEntity.ArcParams.is_clockwise', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=488,
)

_CIRCLEARCENTITY = _descriptor.Descriptor(
  name='CircleArcEntity',
  full_name='CircleArcEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_construction', full_name='CircleArcEntity.is_construction', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='center', full_name='CircleArcEntity.center', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='circle_params', full_name='CircleArcEntity.circle_params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arc_params', full_name='CircleArcEntity.arc_params', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CIRCLEARCENTITY_CIRCLEPARAMS, _CIRCLEARCENTITY_ARCPARAMS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='additional_params', full_name='CircleArcEntity.additional_params',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=202,
  serialized_end=509,
)

_POINTENTITY.fields_by_name['point'].message_type = _VECTOR
_LINEENTITY.fields_by_name['start'].message_type = _VECTOR
_LINEENTITY.fields_by_name['end'].message_type = _VECTOR
_CIRCLEARCENTITY_CIRCLEPARAMS.containing_type = _CIRCLEARCENTITY
_CIRCLEARCENTITY_ARCPARAMS.fields_by_name['start'].message_type = _VECTOR
_CIRCLEARCENTITY_ARCPARAMS.fields_by_name['end'].message_type = _VECTOR
_CIRCLEARCENTITY_ARCPARAMS.containing_type = _CIRCLEARCENTITY
_CIRCLEARCENTITY.fields_by_name['center'].message_type = _VECTOR
_CIRCLEARCENTITY.fields_by_name['circle_params'].message_type = _CIRCLEARCENTITY_CIRCLEPARAMS
_CIRCLEARCENTITY.fields_by_name['arc_params'].message_type = _CIRCLEARCENTITY_ARCPARAMS
_CIRCLEARCENTITY.oneofs_by_name['additional_params'].fields.append(
  _CIRCLEARCENTITY.fields_by_name['circle_params'])
_CIRCLEARCENTITY.fields_by_name['circle_params'].containing_oneof = _CIRCLEARCENTITY.oneofs_by_name['additional_params']
_CIRCLEARCENTITY.oneofs_by_name['additional_params'].fields.append(
  _CIRCLEARCENTITY.fields_by_name['arc_params'])
_CIRCLEARCENTITY.fields_by_name['arc_params'].containing_oneof = _CIRCLEARCENTITY.oneofs_by_name['additional_params']
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['PointEntity'] = _POINTENTITY
DESCRIPTOR.message_types_by_name['LineEntity'] = _LINEENTITY
DESCRIPTOR.message_types_by_name['CircleArcEntity'] = _CIRCLEARCENTITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'cad_model2_pb2'
  # @@protoc_insertion_point(class_scope:Vector)
  })
_sym_db.RegisterMessage(Vector)

PointEntity = _reflection.GeneratedProtocolMessageType('PointEntity', (_message.Message,), {
  'DESCRIPTOR' : _POINTENTITY,
  '__module__' : 'cad_model2_pb2'
  # @@protoc_insertion_point(class_scope:PointEntity)
  })
_sym_db.RegisterMessage(PointEntity)

LineEntity = _reflection.GeneratedProtocolMessageType('LineEntity', (_message.Message,), {
  'DESCRIPTOR' : _LINEENTITY,
  '__module__' : 'cad_model2_pb2'
  # @@protoc_insertion_point(class_scope:LineEntity)
  })
_sym_db.RegisterMessage(LineEntity)

CircleArcEntity = _reflection.GeneratedProtocolMessageType('CircleArcEntity', (_message.Message,), {

  'CircleParams' : _reflection.GeneratedProtocolMessageType('CircleParams', (_message.Message,), {
    'DESCRIPTOR' : _CIRCLEARCENTITY_CIRCLEPARAMS,
    '__module__' : 'cad_model2_pb2'
    # @@protoc_insertion_point(class_scope:CircleArcEntity.CircleParams)
    })
  ,

  'ArcParams' : _reflection.GeneratedProtocolMessageType('ArcParams', (_message.Message,), {
    'DESCRIPTOR' : _CIRCLEARCENTITY_ARCPARAMS,
    '__module__' : 'cad_model2_pb2'
    # @@protoc_insertion_point(class_scope:CircleArcEntity.ArcParams)
    })
  ,
  'DESCRIPTOR' : _CIRCLEARCENTITY,
  '__module__' : 'cad_model2_pb2'
  # @@protoc_insertion_point(class_scope:CircleArcEntity)
  })
_sym_db.RegisterMessage(CircleArcEntity)
_sym_db.RegisterMessage(CircleArcEntity.CircleParams)
_sym_db.RegisterMessage(CircleArcEntity.ArcParams)


# @@protoc_insertion_point(module_scope)
